-- CreateEnum
CREATE TYPE "Role" AS ENUM ('ADMINISTRATOR', 'RECEPTIONIST', 'TRIAGE_NURSE', 'CLINICIAN', 'LAB_STAFF', 'PHARMACIST', 'BILLING_CASHIER', 'NURSING_STAFF', 'PROCUREMENT_STAFF', 'ACCOUNTS_STAFF', 'HR_STAFF');

-- CreateTable
CREATE TABLE "User" (
    "id" TEXT NOT NULL,
    "name" TEXT NOT NULL,
    "email" TEXT NOT NULL,
    "passwordHash" TEXT NOT NULL,
    "role" "Role" NOT NULL,
    "isActive" BOOLEAN NOT NULL DEFAULT true,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "User_pkey" PRIMARY KEY ("id")
);

-- CreateIndex
CREATE UNIQUE INDEX "User_email_key" ON "User"("email");
